services:
  web:
    build: .
    env_file: django/.env
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
    volumes:
      - .:/code

  web_migrate:
    extends:
      service: web
    command: python /code/django/manage.py migrate
    depends_on:
      - db

  web_run:
    extends:
      service: web
    command: python /code/django/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - web_migrate

  db:
    image: postgres:16.3
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
